// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/myproject/shop/internal/Auth"
	"github.com/myproject/shop/internal/Cart"
	"github.com/myproject/shop/internal/Comment"
	"github.com/myproject/shop/internal/Coordinator"
	"github.com/myproject/shop/internal/Order"
	"github.com/myproject/shop/internal/Shop"
	"github.com/myproject/shop/internal/User"
	"github.com/myproject/shop/internal/config"
	"github.com/myproject/shop/internal/search"
	"github.com/myproject/shop/internal/search/order"
	"github.com/myproject/shop/internal/search/product"
	"github.com/myproject/shop/pkg/database"
	"github.com/myproject/shop/pkg/middleware"
	"gorm.io/gorm"
	"log"
)

// Injectors from wire.go:

// InitializeApp 是我们要生成的“总构造函数”
func InitializeApp(cfg *cpnfig.Config) (*Application, error) {
	database, err := provideDB(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := user.NewRepository(database)
	userService := user.NewService(userRepository)
	userHandle := user.NewUserHandle(userService)
	redisStore := provideRedisStore(cfg)
	authService := auth.NewAuthService(userRepository, redisStore)
	authHandler := auth.NewAuthHandler(authService)
	orderRepository := Order.NewRepository(database)
	orderService := Order.NewOrderService(orderRepository)
	orderHandler := Order.NewOrderHandler(orderService)
	shopRepository := shop.NewRepository(database)
	shopService := shop.NewShopService(shopRepository, redisStore)
	shopHandler := shop.NewShopHandler(shopService)
	db := provideGormDB(database)
	service := product.NewService(db)
	ordersearchService := ordersearch.NewService(db)
	handler := search.NewHandler(service, ordersearchService)
	commentRepository := comment.NewRepository(database)
	commentService := comment.NewCommentService(commentRepository)
	commentHandler := comment.NewCommentHandler(commentService)
	cartRepository := cart.NewCartRepository(database)
	cartService := cart.NewCartService(cartRepository)
	cartHandler := cart.NewCartHandler(cartService)
	checkoutService := Coordinator.NewCheckoutService(db, orderService, shopService)
	tradeHandler := Coordinator.NewTradeHandler(checkoutService)
	application := NewApplication(cfg, userHandle, authHandler, orderHandler, shopHandler, handler, commentHandler, cartHandler, tradeHandler)
	return application, nil
}

// wire.go:

func provideRedisStore(cfg *cpnfig.Config) *middleware.RedisStore {
	store := middleware.NewRedisStore(
		cfg.Redis.Addr,
		cfg.Redis.Password,
		cfg.Redis.DB,
	)
	middleware.InitRedis(store.Client)
	return store
}

func provideDB(cfg *cpnfig.Config) (*database.Database, error) {
	db, err := database.NewDB(cfg.Database.BuildPostgresDSN("disable"))
	if err != nil {
		log.Fatal(err)
		return db, err
	}
	if err := db.AutoMigrate(&Order.Order{}, &Order.OrderItem{},
		&shop.Shop{}, &shop.Product{},
		&shop.Category{}, &user.User{}, &comment.Comment{},
		&cart.CartItem{},
	); err != nil {
		log.Fatal(err)
		return db, err
	}
	return db, err

}

func provideGormDB(db *database.Database) *gorm.DB {
	return db.DB
}
